version: "3"

networks:
  pizzashop:

services:
  bakery:
    build: 
        context: bakery
    ports:
      - "9000:9000"
    networks:
      - pizzashop

  postgres:
    build:
        context: postgres
    ports: 
      - "5432:5432"
    environment:
        - BAKERY_PASSWORD='abcd'
        - POSTGRES_PASSWORD="password!"
    networks:
      - pizzashop
