// Code generated by sqlc. DO NOT EDIT.

package storage

import (
	"fmt"
	"time"

	"github.com/jackc/pgtype"
)

type StatusEnum string

const (
	StatusEnumPreparing StatusEnum = "preparing"
	StatusEnumBaking    StatusEnum = "baking"
	StatusEnumDone      StatusEnum = "done"
)

func (e *StatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StatusEnum(s)
	case string:
		*e = StatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for StatusEnum: %T", src)
	}
	return nil
}

type Bake struct {
	ID         pgtype.UUID
	CreateTime time.Time
	Name       string
	BakeStatus StatusEnum
}

type Topping struct {
	ID pgtype.UUID
}
