apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.23.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: bakery
  name: bakery
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bakery
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.23.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/pizzashop: "true"
        io.kompose.service: bakery
    spec:
      containers:
        - image: bakery
          name: bakery
          ports:
            - containerPort: 9000
          resources: {}
      restartPolicy: Always
status: {}
