apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.23.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: bakery
  name: bakery
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bakery
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.23.0 (HEAD)
      labels:
        io.kompose.network/pizzashop: "true"
        io.kompose.service: bakery
    spec:
      containers:
        - image: bakery-service:v1
          name: bakery
          ports:
            - containerPort: 10000
          args:
            - "-postgres-url=postgresql://bakery_user:abcd@postgres:5432/bakery"
          resources: {}    
          livenessProbe:
            failureThreshold: 3
            exec:
            # considers both SERVING and NOT SERVING to be a success
              command: ["/bin/sh", "-c", "/bin/grpc_health_probe -addr=:10000 2>&1 | grep -q SERVING"]
            initialDelaySeconds: 240
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 15
          readinessProbe:
            failureThreshold: 3
            exec:
              # fails on any response except SERVING
              command: ["/bin/grpc_health_probe", "-addr=:10000"]
            initialDelaySeconds: 20
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 15
          restartPolicy: Always
